name: Testing suite

on:
    workflow_dispatch:
    push:
        branches:
            - master
            - development
    pull_request:
        branches:
            - master

jobs:
    unit-test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                php-versions: ['7.4']
        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, intl, zip

            - name: Composer install
              run: (rm composer.lock || true) &&  composer update

            - name: PHP version
              run: php --version

            - name: Run tests
              run: composer run testdox
